spring:
  application:
    name: JWTAuth

  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:authDB

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5000

JWTAuth:
  app:
    secret: thisisthesecretkeyhaathnahilagana256charactersejyadahonichaiye
    expirationMS: 86400000